"use client";

export type { AppIcon } from "@/lib/icons/types";

export {
  Pulse as Activity,
  ArrowRight,
  ArrowUpRight,
  BookOpen,
  Books,
  Books as Library,
  Briefcase,
  Calendar,
  CalendarCheck as CalendarClock,
  CaretRight,
  CaretRight as ChevronRight,
  ChartBar,
  ChartBar as BarChart3,
  ChartPie,
  ChartPie as LayoutDashboard,
  ChatCircle,
  ChatCircle as MessageSquare,
  ChatsCircle,
  ChatsCircle as MessageCircle,
  Check,
  ClipboardText,
  Clock,
  CreditCard,
  Flask,
  Flask as Beaker,
  Flask as FlaskConical,
  FolderOpen,
  GraduationCap,
  Heart,
  Lightbulb,
  List,
  List as Menu,
  MagnifyingGlass,
  MagnifyingGlass as Search,
  Medal,
  Medal as Award,
  Presentation,
  ShieldCheck,
  SignOut,
  SignOut as LogOut,
  Sparkle,
  Sparkle as Sparkles,
  Star,
  Stethoscope,
  Student,
  Student as School,
  Tray,
  Tray as Inbox,
  TrendUp,
  TrendUp as TrendingUp,
  Trophy,
  User,
  UserCircle,
  Users,
  Video,
  Wallet,
  Wrench,
  X,
} from "@phosphor-icons/react";
